version: "3.9"
services:
  postgres:
    image: library/postgres:13
    container_name: postgres
    restart: on-failure
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./postgres/:/docker-entrypoint-initdb.d/
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready", "-U", "postgres", "-d", "postgres"]

  rabbit:
    image: rabbitmq:3.9.2-management-alpine
    container_name: rabbit
    ports:
      - "15672:15672"
      - "5672:5672"
    volumes:
      - "./rabbitmq/data/:/var/lib/rabbitmq/"
      - "./rabbitmq/log/:/var/log/rabbitmq/"
    healthcheck:
      test: ["CMD-SHELL", "rabbitmq-diagnostics check_local_alarms"]

  api-gateway:
    build:
      context: .
      dockerfile: ./src/FlightBooking.Gateway/Dockerfile
    image: maxkozlov/rsoi-api-gateway:1.0
    container_name: api-gateway
    restart: on-failure
    ports:
      - "8080:8080"
    depends_on:
      - flight-service
      - bonus-service
      - ticket-service
      - rabbit
    healthcheck:
      test: "wget -nv -t1 --spider localhost:8080/manage/health/liveness"

  ticket-service:
    build:
      context: .
      dockerfile: ./src/FlightBooking.TicketService/Dockerfile
    image: maxkozlov/rsoi-ticket-service:1.0
    container_name: ticket-service
    restart: on-failure
    ports:
      - "8070:8070"
    depends_on:
      - postgres
    healthcheck:
      test: "wget -nv -t1 --spider localhost:8070/manage/health/liveness"

  flight-service:
    build:
      context: .
      dockerfile: ./src/FlightBooking.FlightService/Dockerfile
    image: maxkozlov/rsoi-flight-service:1.0
    container_name: flight-service
    restart: on-failure
    ports:
      - "8060:8060"
    depends_on:
      - postgres
    healthcheck:
      test: "wget -nv -t1 --spider localhost:8060/manage/health/liveness"

  bonus-service:
    build:
      context: .
      dockerfile: ./src/FlightBooking.BonusService/Dockerfile
    image: maxkozlov/rsoi-bonus-service:1.0
    container_name: bonus-service
    restart: on-failure
    ports:
      - "8050:8050"
    depends_on:
      - postgres
      - rabbit
    healthcheck:
      test: "wget -nv -t1 --spider localhost:8050/manage/health/liveness"

volumes:
  db-data: