apiVersion: v1
kind: Service
metadata:
  name: load-blancer
spec:
  ports:
  # Порт сетевого балансировщика, на котором будут обслуживаться пользовательские запросы.
  - protocol: TCP
    port: 80
    # Порт контейнера, на котором доступно приложение.
    targetPort: 8080
  # Метки селектора, использованные в шаблоне подов при создании объекта Deployment.
  selector:
    app: gateway
  type: LoadBalancer