name: GitHub Classroom Workflow
on:
  push:
    branches: [ master ]

env:
  KUBE_URL: ${{ secrets.KUBE_URL }}
  KUBE_TOKEN: ${{ secrets.KUBE_TOKEN }}

jobs:
  build:
    name: Autograding
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: docker/setup-buildx-action@v2

      # - name: Login to Docker Hub
      #   uses: docker/login-action@v2
      #   with:
      #     username: ${{ secrets.DOCKERHUB_USERNAME }}
      #     password: ${{ secrets.DOCKERHUB_TOKEN }}

      # TODO build, publish to docker hub, deploy to k8s
      - name: Build and publish images
        timeout-minutes: 15
        run: |
          echo "$KUBE_URL"

      # ./scripts/build-images.sh
      
      - uses: actions-hub/kubectl@1.14.3
        env:
          KUBE_HOST: ${{ secrets.KUBE_HOST }}
          KUBE_CERTIFICATE: ${{ secrets.KUBE_CERTIFICATE }}
          KUBE_TOKEN: ${{ secrets.KUBE_TOKEN }}
        with:
          args: get pods
        continue-on-error: true

      - name: Deploy
        run: |
          echo "run deploy"
          kubectl config set-cluster rsoi-flights-service-cluster --server="$KUBE_URL" --insecure-skip-tls-verify=true
          kubectl config set-credentials cloud_okteto_com-user --token="$KUBE_TOKEN"
          kubectl config set-context default --cluster=rsoi-flights-service-cluster --user=cloud_okteto_com-user --namespace="maxim-kozlov"
          kubectl get pods

          cd k8s && (helm delete services | true) && helm install services ./services-chart/
          sleep 45
        continue-on-error: true
        
      - name: Run API Tests
        uses: matt-ball/newman-action@master
        with:
          collection: v1/postman/collection.json
          environment: v1/postman/environment.json
          delayRequest: 100
          reporters: '[ "cli" ]'

      - uses: education/autograding@v1
        id: autograder
        continue-on-error: true

      - name: Github auto grader mark
        uses: Romanow/google-sheet-autograder-marker@v1.0
        with:
          google_token: ${{secrets.GOOGLE_API_KEY}}
          sheet_id: "1xkgjUX6Qmk7rdJG-QPOToav-HWWtthJjnShIKnw3oIY"
          homework_number: 4
          user_column: 'D'
          column_offset: 'F'
          mark: "'+"